#docker compose -f "DOCKER-COMPOSE.yaml" up -d --build
version: '3'
services:
    landing:
        container_name: landing
        image: nginx:stable-alpine
        mem_limit: 128m
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./:/usr/share/nginx/html:ro